### ISSUE TITLE
Визуальные проблемы

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [Fingercomp/python-utils#1]
Так как ты сказал мне `[15:09:28] <fingercomp> 2. https://github.com/Fingercomp/python-utils/issues`, я пишу сюда. Итак, текущие проблемы:
- [ ] Ширина юзерлиста и кнопок под ним не фиксирована из-за сеточного интерфейса.
- [x] При запуске выделяется первый лейбл с временем.

**Comment by Fingercomp** [comment]
1. Такое чувство, что Gtk издевается. Ни в какую не хочет указывать да хотя бы минимальный размер сайдбара.
2. Пытаюсь отыскать что-нибудь по этому поводу. Ничего пока не работает.

**Comment by Fingercomp** [comment]
Как и положено, "починил" проблему костылём. Добавил лейбл пустой, выставил `set_selectable(True)`. Отступ, правда, остался.
Что делать с боковой панелью, ума не приложу. Она упорно едет куда-то в тридевятое царство.

**Comment by Fingercomp** [comment]
Пошерстил я тут интернеты. Короче, первый пункт можно сделать **только** с помощью `Gtk.Table`, который устарел.

> **Deprecated since version 3.4:** Use Gtk.Grid.attach () with Gtk.Grid. Note that the attach arguments differ between those two functions.

([Source](http://lazka.github.io/pgi-docs/Gtk-3.0/classes/Table.html#Gtk.Table.attach))
Собственно, именно одного из нужных аргументов и нет. А я категорически против использования устаревших фишек.

**Comment by Fingercomp** [comment]
[Найдено](http://i.imgur.com/X5bI94V.png). ;-)
Будет сделано, похоже.

**Comment by Fingercomp** [comment]
Поковырялся. Что ж, не получится. Этот отступ я не могу никак убрать. Оставлю пока динамически.

**Comment by YuRaNnNzZZ** [comment]
Не полностью пофиксил - переоткрывай.

**Comment by Fingercomp** [comment]
А смысл? Всё равно я никак не сделаю. Но открою, ладно.

**Comment by YuRaNnNzZZ** [comment]
Короче, хрен с ней, с этой шириной. Сделай просто юзерлисту возможность менять ширину вручную, да и всё.

**Comment by Fingercomp** [comment]
Если бы! Так нельзя ж.

**Comment by YuRaNnNzZZ** [comment]
предлагаю попробовать сделать отдельную версию чятиков для виндовозов на ткинтере (хотя бы без иконки в трее)

**Comment by Fingercomp** [comment]
Флаг тебе в руки и вперёд, жду пулл реквеста. Я не буду переходить на ткинтер, хотя бы потому, что я его не знаю.
