### ISSUE TITLE
[ffgs-chat] Обновление системы авторизации

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [Fingercomp/python-utils#13]
Со вчерашнего дня сайт теперь принимает другие куки:
`auth_user` - id юзера, которым нужно авторизоваться
`auth_hash` - хеш юзера
Куки хранятся месяц, юзер не деавторизуется рандомно, `PHPSESSID` теперь не постоянный (вроде).

**Comment by YuRaNnNzZZ** [comment]
в README.md исправь

**Comment by Fingercomp** [comment]
Уже
