### ISSUE TITLE
[ffgs-chat] Ошибка при первом запуске

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [Fingercomp/python-utils#16]
Решил переставить питон и пугтк с нуля, заодно грохнул конфиги твоих прог.
Запустил чятик, он написал, что конфиг создан... и вылетел.

```
Traceback (most recent call last):
  File "C:\ffgs-chat.py", line 84, in <module>
    "Cookie": "auth_user=" + userdata[0] + "; auth_hash=" + userdata[1]
IndexError: list index out of range
```

(скорее всего это связано с тем, что конфиг стал многострочным)

**Comment by Fingercomp** [comment]
По поводу конфигов сделал #17 ещё — а пока нужно действовать по инструкции в README.
