### ISSUE TITLE
HTML-теги

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [Fingercomp/python-utils#5]
Клиент не обрабатывает HTML-теги, в итоге получается это:
![](https://i.imgur.com/EcPwcuq.png)
На сайте это выглядит так: ![](https://i.imgur.com/oxVqSeZ.png)
Список используемых тегов: `<span class="spoiler">`, `<strong>`, `<em>`, `<span style="text-decoration: underline;">`, `<span style="text-decoration: line-through;">`, `<span style="text-decoration: overline;">`.

**Comment by YuRaNnNzZZ** [comment]
Предлагаю либо обрезать их вообще, либо прикрутить базовую обработку.

**Comment by Fingercomp** [comment]
In progress.
![Current progress](http://i.imgur.com/EKl6kga.png)
