### ISSUE TITLE
Нет картинки в Windows

### ISSUE THREAD

**Issue by Fingercomp** [Fingercomp/python-utils#8]
Иконка в трее без какой-либо картинки на Windows. Надо прикрутить ввод её из файла. И придумать, как не таскать с собою тонну файлов. И чтоб компактно было.
- [x] Сделать картинки
- [x] Подключить картинки в программы
  - [x] ffgs-chat
  - [x] cc-chat
  - [x] mc-monitor
- [x] Скачивание картинок

**Comment by YuRaNnNzZZ** [comment]
Я нашёл [вот это](http://sourceforge.net/projects/gtk-win/files/GTK%2B%20Themes%20Package/2009-09-07/gtk2-themes-2009-09-07-win32_bin.zip/download), но сомневаюсь, что оно будет работать с GTK 3+.
